### ISSUE TITLE
Create larsroettig / pwa-studio-component-override-resolver ;)

### ISSUE THREAD

**Issue by 0m3r** [larsroettig/pwa-studio-component-override#1]
It's a  cool article and video. Thanks you for your work.

I think it is a next step it is to have one place for intercept

yarn add larsroettig/@pwa-studio-component-override-resolver

so need to create a standalone package pwa-studio-component-override-resolver.
- it will parse all dependent packages and check at file exist src/moduleOverrideWebpackPlugin.js
- merge all overrides into array
- check conflicts 
- etc

**Comment by larsroettig** [comment]
@0m3r  is already built but not  by me https://github.com/fooman/venia-ui-override-resolver

**Comment by larsroettig** [comment]
But I think he doesn't check about override conflicts
